#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 & # Start sxhkd after setting the keyboard layout for non QWERTYs

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color        "#F1CB7E"
# bspc config normal_border_color         "#073642"
# bspc config active_border_color         "#FF0000"


### Window rules
# bspc rule -a 2ndclass:firstclass:"title" sticky=on state=floating
# hidden - Is hidden and doesn’t occupy any tiling space.
# sticky - Stays in the focused desktop of its monitor.
# private - Tries to keep the same tiling position/size.
# locked - Ignores the node --close message.
# marked - Is marked (useful for deferred actions). A marked node becomes unmarked after being sent on a preselected node.
# center - Center window if state=floating.
# follow - Change to monitor/desktop of window.
# manage - Window is managed. An unmanaged window is not part of the tree.
# focus - Focus the window.
# border - Visibility of the window border.

# Desktop
bspc rule -a code-oss desktop='^1'

bspc rule -a *:Navigator desktop='^2' # Any web browser

bspc rule -a social:Navigator desktop='^3' # Social firefox profile
bspc rule -a FreeTube desktop='^3' state=tiled

bspc rule -a obsidian desktop='^4'

bspc rule -a krita desktop='^5'
bspc rule -a Darktable desktop='^5'
bspc rule -a Rawtherapee desktop='^5'
bspc rule -a Pinta desktop='^5'
bspc rule -a digikam desktop='^5'
bspc rule -a Aseprite desktop='^5'
bspc rule -a photoshop.exe desktop='^5'

bspc rule -a Signal desktop='^6'

bspc rule -a SDConsole desktop='^7'

bspc rule -a Yad desktop='^8' state=floating follow=on # Stl
bspc rule -a streaming_client desktop='^8' # Steam remoteplay
bspc rule -a overwatch.exe desktop='^8'
bspc rule -a "Minecraft*" desktop='^8'
bspc rule -a wow-64.exe desktop='^8'
bspc rule -a wow.exe desktop='^8'

bspc rule -a stratz desktop='^9'
bspc rule -a Steam desktop='^9' state=tiled follow=off
bspc rule -a steam desktop='^9' state=tiled follow=off
bspc rule -a steamwebhelper desktop='^9' state=tiled follow=off
bspc rule -a steamwebhelper:steamwebhelper:"Special Offers" desktop='^9' state=floating follow=off
bspc rule -a bottles desktop='^9' follow=off
bspc rule -a PrismLauncher desktop='^9' follow=off
bspc rule -a battle.net.exe desktop='^9' follow=off
bspc rule -a WowUpCf desktop='^9' follow=off


# Special
bspc rule -a Pavucontrol state=floating
bspc rule -a Gpick state=floating
bspc rule -a Signal:signal:"Sharing screen" sticky=on state=floating
bspc rule -a firefox:Toolkit state=floating sticky=on rectangle=210x120
bspc rule -a *:*:"Picture in picture" state=floating sticky=on rectangle=640x360
bspc rule -a *:*:"Picture-in-Picture" state=floating sticky=on rectangle=640x360

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


### Autostart
# 1080p resolution
# xrandr --output Virtual-1 --mode 1920x1080 --rate 144

# Numlock
numlockx

# Compositor
picom -b

# Polybar
sh "$HOME/.config/polybar/launch.sh" &

# Background
feh ~/.icons/wallpaper/shinjuku-tokyo-mimimal-4k-o8.jpg --bg-fill

# ICC Profile
# xcalib /mnt/four/data/download/asus_vg248qe_svet.icm

# Launch the ckb-next-daemon
# ckb-next-daemon &

# Launch CKB and close immediately
if ! pidof -x "ckb-next" >/dev/null; then
	ckb-next &
fi
